# ===============================
#       Server Configuration
# ===============================
server.port=${PORT:8080}
#server.servlet.context-path=/

# ===============================
#   MySQL Database Configuration
# ===============================
JDBC_DRIVER=com.mysql.cj.jdbc.Driver
JDBC_URL=${MYSQL_URL}
JDBC_USER=${MYSQL_USER}
JDBC_PASSWORD=${MYSQL_PASSWORD}
JDBC_HOST=${MYSQL_HOST}
JDBC_PORT=${MYSQL_PORT}

DATABASE_NAME=${MYSQL_DB_NAME}
DB_SCHEMA_FILE=schema.sql

# ===============================
#   SMTP Mail Configuration
# ===============================
mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
mail.name=${MAIL_NAME}
mail.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
https.protocols=TLSv1.2

# ===============================
#   CLOUDINARY SECRETS
# ===============================
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

# ===============================
#   WEBSOCKET URL
# ===============================
LIVE_VOTE_COUNT_WS_URL=${WS_URL}

# ===============================
#   Other Configs
# ===============================
SKIP_ESSENTIAL_FOLDER_INIT=true
REQUIRED_FOLDER_INITIALIZATION_BEFORE_STARTUP=${REQUIRED_INIT_PATHS}
