status = error
name = PropertiesConfig

# =======================================
#   LOG4J FILE DIRECTORY (TELEGRAM)
# =======================================

# Console appender
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M:%L)%n

# Telegram appender
appender.telegram.type = TelegramAppender
appender.telegram.name = TelegramAppender

appender.telegram.botToken = ${env:BOT_TOKEN}
appender.telegram.chatId = ${env:CHAT_ID}

appender.telegram.layout.type = PatternLayout
appender.telegram.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M)%n

# Add a ThresholdFilter to TelegramAppender to ignore DEBUG
appender.telegram.filter.threshold.type = ThresholdFilter
appender.telegram.filter.threshold.level = error
appender.telegram.filter.threshold.onMatch = ACCEPT
appender.telegram.filter.threshold.onMismatch = DENY

# Root logger
rootLogger.level = debug
rootLogger.appenderRefs = console, telegram
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.telegram.ref = TelegramAppender