status = error
name = PropertiesConfig

# =======================================
#   LOG4J FILE DIRECTORY (TELEGRAM)
# =======================================

# Console appender
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M:%L)%n

# Telegram appender
appender.telegram.type = TelegramAppender
appender.telegram.name = TelegramAppender
appender.telegram.botToken = ${BOT_TOKEN}
appender.telegram.chatId = ${CHAT_ID}
appender.telegram.layout.type = PatternLayout
appender.telegram.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M)%n

# Add a ThresholdFilter to TelegramAppender to ignore DEBUG
appender.telegram.filter.threshold.type = ThresholdFilter
appender.telegram.filter.threshold.level = error
appender.telegram.filter.threshold.onMatch = ACCEPT
appender.telegram.filter.threshold.onMismatch = DENY

# Root logger
rootLogger.level = debug
rootLogger.appenderRefs = console, telegram
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.telegram.ref = TelegramAppender

# =======================================
#   LOG4J FILE DIRECTORY (LOCAL)
# =======================================
#property.basePath = /Users/shivamthakur/VOTESPHERE-RESOURCES/LOGS


## Console Appender
#appender.console.type = Console
#appender.console.name = ConsoleAppender
#appender.console.layout.type = PatternLayout
#appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M)%n
#
## Appender for DEBUG
#appender.debug.type = RollingFile
#appender.debug.name = DebugFile
#appender.debug.fileName = ${basePath}/app-debug.log
#appender.debug.filePattern = ${basePath}/app-debug-%d{yyyy-MM-dd}-%i.log.gz
#appender.debug.layout.type = PatternLayout
#appender.debug.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level [%logger{36}] - %msg :: (%M)%n
#appender.debug.policies.type = Policies
#appender.debug.policies.time.type = TimeBasedTriggeringPolicy
#appender.debug.policies.size.type = SizeBasedTriggeringPolicy
#appender.debug.policies.size.size = 10MB
#appender.debug.filter.level.type = LevelRangeFilter
#appender.debug.filter.level.minLevel = DEBUG
#appender.debug.filter.level.maxLevel = DEBUG
#appender.debug.filter.level.onMatch = ACCEPT
#appender.debug.filter.level.onMismatch = DENY
#
## Appender for INFO
#appender.info.type = RollingFile
#appender.info.name = InfoFile
#appender.info.fileName = ${basePath}/app-info.log
#appender.info.filePattern = ${basePath}/app-info-%d{yyyy-MM-dd}-%i.log.gz
#appender.info.layout.type = PatternLayout
#appender.info.layout.pattern =  %d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg :: (%M)%n
#appender.info.policies.type = Policies
#appender.info.policies.time.type = TimeBasedTriggeringPolicy
#appender.info.policies.size.type = SizeBasedTriggeringPolicy
#appender.info.policies.size.size = 10MB
#appender.info.filter.threshold.type = ThresholdFilter
#appender.info.filter.threshold.level = INFO
#
## Appender for WARN
#appender.warn.type = RollingFile
#appender.warn.name = WarnFile
#appender.warn.fileName = ${basePath}/app-warn.log
#appender.warn.filePattern = ${basePath}/app-warn-%d{yyyy-MM-dd}-%i.log.gz
#appender.warn.layout.type = PatternLayout
#appender.warn.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level [%logger{36}] - %msg :: (%M)%n
#appender.warn.policies.type = Policies
#appender.warn.policies.time.type = TimeBasedTriggeringPolicy
#appender.warn.policies.size.type = SizeBasedTriggeringPolicy
#appender.warn.policies.size.size = 10MB
#appender.warn.filter.threshold.type = ThresholdFilter
#appender.warn.filter.threshold.level = WARN
#
## Appender for ERROR
#appender.error.type = RollingFile
#appender.error.name = ErrorFile
#appender.error.fileName = ${basePath}/app-error.log
#appender.error.filePattern = ${basePath}/app-error-%d{yyyy-MM-dd}-%i.log.gz
#appender.error.layout.type = PatternLayout
#appender.error.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level [%logger{36}] - %msg :: (%M)%n
#appender.error.policies.type = Policies
#appender.error.policies.time.type = TimeBasedTriggeringPolicy
#appender.error.policies.size.type = SizeBasedTriggeringPolicy
#appender.error.policies.size.size = 10MB
#appender.error.filter.threshold.type = ThresholdFilter
#appender.error.filter.threshold.level = ERROR
#
## Appender for FATAL
#appender.fatal.type = RollingFile
#appender.fatal.name = FatalFile
#appender.fatal.fileName = ${basePath}/app-fatal.log
#appender.fatal.filePattern = ${basePath}/app-fatal-%d{yyyy-MM-dd}-%i.log.gz
#appender.fatal.layout.type = PatternLayout
#appender.fatal.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level [%logger{36}] - %msg :: (%M)%n
#appender.fatal.policies.type = Policies
#appender.fatal.policies.time.type = TimeBasedTriggeringPolicy
#appender.fatal.policies.size.type = SizeBasedTriggeringPolicy
#appender.fatal.policies.size.size = 10MB
#appender.fatal.filter.threshold.type = ThresholdFilter
#appender.fatal.filter.threshold.level = FATAL
#
## Logger
#logger.voteSphere.name = com.voteSphere
#logger.voteSphere.level = debug
#logger.voteSphere.additivity = false
#logger.voteSphere.appenderRefs = console, debug, info, warn, error, fatal
#logger.voteSphere.appenderRef.console.ref = ConsoleAppender
#logger.voteSphere.appenderRef.debug.ref = DebugFile
#logger.voteSphere.appenderRef.info.ref = InfoFile
#logger.voteSphere.appenderRef.warn.ref = WarnFile
#logger.voteSphere.appenderRef.error.ref = ErrorFile
#logger.voteSphere.appenderRef.fatal.ref = FatalFile
#
## Root logger (for any uncaught packages)
#rootLogger.level = info
#rootLogger.appenderRefs = console
#rootLogger.appenderRef.console.ref = ConsoleAppender
