name: Deploy to AWS VM

on:
  push:
    branches: [ pushkar-dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: pushkar-dev

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to AWS VM
        run: |
          # Create properties files with secrets
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > application.properties
          echo "${{ secrets.LOG4J2_PROPERTIES }}" > log4j2.properties
          
          # Copy project files
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:voteSphere
          
          # Copy properties files to correct location
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p voteSphere/src/main/resources"
          scp -o StrictHostKeyChecking=no application.properties ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:voteSphere/src/main/resources/
          scp -o StrictHostKeyChecking=no log4j2.properties ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:voteSphere/src/main/resources/

      - name: Execute deployment commands on AWS VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Step 1: Install Java (OpenJDK 21)
          sudo apt update
          sudo apt install openjdk-21-jdk -y
          
          # Step 2: Install Maven
          sudo apt install maven -y
          
          # Step 3: Download and Set Up Apache Tomcat 11
          cd /opt
          sudo wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M20/bin/apache-tomcat-11.0.0-M20.tar.gz
          sudo tar -xzf apache-tomcat-11.0.0-M20.tar.gz
          sudo mv apache-tomcat-11.0.0-M20 tomcat
          sudo chmod +x /opt/tomcat/bin/*.sh
          
          # Step 4: Project already copied by previous step
          cd voteSphere
          
          # Step 5: Build the Project Using Maven
          mvn clean package
          
          # Step 6: Deploy the WAR File to Tomcat Root Context
          sudo cp target/voteSphere.war /opt/tomcat/webapps/ROOT.war
          
          # Step 7: Restart Tomcat
          /opt/tomcat/bin/shutdown.sh || true
          /opt/tomcat/bin/startup.sh
          EOF